# Generated by Django 6.0.6 on 2026-07-07 07:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_profile_tenant_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('type', models.CharField(choices=[('DIRECT_MESSAGE', 'Direct Message'), ('TENANT_CHATS', 'Tenant Chats'), ('BROADCAST', 'Broadcast')], default='BROADCAST')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chats.chatrooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now=True)),
                ('last_read_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_read', to='chats.messages')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chats.chatrooms')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chats.roommembers'),
        ),
        migrations.AddConstraint(
            model_name='chatrooms',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='unique_constraint_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='roommembers',
            constraint=models.UniqueConstraint(fields=('room', 'profile'), name='unique_constraint_room_profile'),
        ),
    ]
