# Generated by Django 6.1 on 2026-09-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='messages',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatrooms'),
        ),
        migrations.AddField(
            model_name='roommembers',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to='core.profile'),
        ),
        migrations.AddField(
            model_name='roommembers',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chats.chatrooms'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.roommembers'),
        ),
        migrations.AddConstraint(
            model_name='chatrooms',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='unique_constraint_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='roommembers',
            constraint=models.UniqueConstraint(fields=('room', 'profile'), name='unique_constraint_room_profile'),
        ),
    ]
